### ISSUE TITLE
Todo's release 4.0

### ISSUE THREAD

**Issue by edenhaus** [And3rsL/Deebot-for-Home-Assistant#222]
The todo's for the next version. Issue exists only for me, so I don't forget something

- [x] add total stats sensors #217
- [x] use authenticator and new clients  #220
- [x] Refactor sensors and use refactored event_bus #221 
- [x] Move rooms attributes to single `rooms` attribute with a dictionary
- [ ] Add `reportStats` as event only when cleaning job is finished
- [ ] Point removed sensors to above event
- [x] `sensor.water_level` -> `select.water_amount` #223

**Comment by edenhaus** [comment]
Not sure if someone is following this issue, but there will be no release 4.0.
But instead there will be a release of [Deebot-4-Home-Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant) soon with all amazing feature from above.

You made ask you, why a new component... More details in https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/7

**Comment by Edo78** [comment]
I'm watching the whole repo and now I'm watching also the other one :+1:

**Comment by aidbish** [comment]
> Not sure if someone is following this issue, but there will be no release 4.0. But instead there will be a release of [Deebot-4-Home-Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant) soon with all amazing feature from above.
> 
> You made ask you, why a new component... More details in [DeebotUniverse/Deebot-4-Home-Assistant#7](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/7)

Lets us know when you want testing done, happy to assist

**Comment by edenhaus** [comment]
First beta release now available, please check out DeebotUniverse/Deebot-4-Home-Assistant#7
